### ISSUE TITLE
Не понятное поведение

### ISSUE THREAD

**Issue by nikosid** [skeeks-semenov/yii2-http-basic-auth#1]
В вашем примере http://gallery.world/ если нажать отмену при запросе пароля, то открывается страница сайта с текстом "Наш сайт в процессе разработки 
Если у вас есть пароль, можно смотреть его тестовую версию."
Разве это верное поведение http аутинтификации?

**Comment by skeeks-semenov** [comment]
@nikosid , да верное.

За это отвечает параметр:
`'viewFail'          => '@app/views/http-basic-auth-fail'    //optionality`

Если его не указать, будет стандартная заглушка, на белом фоне.

Логин пароль. (временный)

semenov
test

**Comment by nikosid** [comment]
Спасибо за ответ, сори за issue, не знал куда написать.
